### ISSUE TITLE
Predicting

### ISSUE THREAD

**Issue by sunprinceS** [We-can-apply-GPU/aMeLiDoSu-HW3#2]
目前implement的方式，是拿來預測下一個字的RNN model
如果要用於predicting，想說可以依空格所在位置分成前半，右半
針對前半，用RNN predict出一個空格的結果，跟每個選項看cosine distance，紀錄之
再來將每個選項放進後半中，去predict出N个字後的位置之結果，再與正確結果看cosine distance，
把兩個cosineˊ distance加起來，最小那個即為Ans.

這是針對目前training data我是怎嚜給有關啦
不過私以為這方式也不甚好，看大家有沒有什麼更好的想法~~
（LSTM感覺來不及做了  RNN光要給个traing data就不簡單了...）

**Comment by danielthank** [comment]
懷念的repo
